# for development
version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:${NGINX_HOST_HTTP_PORT}
    links:
      - php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
  # workspaces
  node_workspace:
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    tty: true
    ports:
      - 8080:8080  # for HMR
      - 9001:9001  # for Storybook
  composer_workspace:
    build:
      context: .
      dockerfile: ./composer/Dockerfile
      args:
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    tty: true
    command: "bash"
