version: '3'
volumes:
  code_share:
services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:${NGINX_HOST_HTTP_PORT}
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm_deploy/Dockerfile
      args:
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - APP_CODE_PATH_HOST=${APP_CODE_PATH_HOST}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    volumes:
        - code_share:/var/www/
